name: Deploy WordPress Theme

env:
  DEBUG: true

on:
  push:
    branches:
      - main # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: wp-content/themes/astra-child/
          target: /var/www/aavsb/
