name: Deploy WordPress Theme

on:
  push:
    branches:
      - main # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy WordPress Theme
        uses: samkirkland/ftp-deploy-action@4.2.0
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: wp-content/themes/astra-child/
          server-dir: wp-content/themes/astra-child/
          method: scp
