name: Deploy WordPress Theme

on:
  push:
    branches:
      - main # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: wp-content/themes/astra-child/
          target: /var/www/html/wp-content/themes/astra-child/
